### ISSUE TITLE
Timezone object returned from convert_raw_time causes pandas plot to fail

### ISSUE THREAD

**Issue by sloveridge** [OrbitalEnterprises/evekit-source-mdtools#1]
The timezone object used in convert_raw_time, datetime.timezone.utc, causes pandas to fail when plotting.

Test case:
Example_1_Data_Extraction_With_Libraries
market_history[market_history.region_id == 10000043].avg_price.plot(title="Tritanium price in Domain", figsize=[10,5])

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-3ee4c00b93db> in <module>()
      1 # and here's the second
----> 2 market_history[market_history.region_id == 10000043].avg_price.plot(title="Tritanium price in Domain", figsize=[10,5])

~/Projects/eve_market/lib/python3.6/site-packages/pandas/plotting/_core.py in __call__(self, kind, ax, figsize, use_index, title, grid, legend, style, logx, logy, loglog, xticks, yticks, xlim, ylim, rot, fontsize, colormap, table, yerr, xerr, label, secondary_y, **kwds)
   2451                            colormap=colormap, table=table, yerr=yerr,
   2452                            xerr=xerr, label=label, secondary_y=secondary_y,
-> 2453                            **kwds)
   2454     __call__.__doc__ = plot_series.__doc__
   2455 

~/Projects/eve_market/lib/python3.6/site-packages/pandas/plotting/_core.py in plot_series(data, kind, ax, figsize, use_index, title, grid, legend, style, logx, logy, loglog, xticks, yticks, xlim, ylim, rot, fontsize, colormap, table, yerr, xerr, label, secondary_y, **kwds)
   1892                  yerr=yerr, xerr=xerr,
   1893                  label=label, secondary_y=secondary_y,
-> 1894                  **kwds)
   1895 
   1896 

~/Projects/eve_market/lib/python3.6/site-packages/pandas/plotting/_core.py in _plot(data, x, y, subplots, ax, kind, **kwds)
   1692         plot_obj = klass(data, subplots=subplots, ax=ax, kind=kind, **kwds)
   1693 
-> 1694     plot_obj.generate()
   1695     plot_obj.draw()
   1696     return plot_obj.result

~/Projects/eve_market/lib/python3.6/site-packages/pandas/plotting/_core.py in generate(self)
    243         self._compute_plot_data()
    244         self._setup_subplots()
--> 245         self._make_plot()
    246         self._add_table()
    247         self._make_legend()

~/Projects/eve_market/lib/python3.6/site-packages/pandas/plotting/_core.py in _make_plot(self)
    918 
    919     def _make_plot(self):
--> 920         if self._is_ts_plot():
    921             from pandas.plotting._timeseries import _maybe_convert_index
    922             data = _maybe_convert_index(self._get_ax(0), self.data)

~/Projects/eve_market/lib/python3.6/site-packages/pandas/plotting/_core.py in _is_ts_plot(self)
    911     def _is_ts_plot(self):
    912         # this is slightly deceptive
--> 913         return not self.x_compat and self.use_index and self._use_dynamic_x()
    914 
    915     def _use_dynamic_x(self):

~/Projects/eve_market/lib/python3.6/site-packages/pandas/plotting/_core.py in _use_dynamic_x(self)
    915     def _use_dynamic_x(self):
    916         from pandas.plotting._timeseries import _use_dynamic_x
--> 917         return _use_dynamic_x(self._get_ax(0), self.data)
    918 
    919     def _make_plot(self):

~/Projects/eve_market/lib/python3.6/site-packages/pandas/plotting/_timeseries.py in _use_dynamic_x(ax, data)
    234         x = data.index
    235         if (base <= frequencies.FreqGroup.FR_DAY):
--> 236             return x[:1].is_normalized
    237         return Period(x[0], freq).to_timestamp(tz=x.tz) == x[0]
    238     return True

pandas/_libs/src/properties.pyx in pandas._libs.lib.cache_readonly.__get__ (pandas/_libs/lib.c:44594)()

~/Projects/eve_market/lib/python3.6/site-packages/pandas/core/indexes/datetimes.py in is_normalized(self)
   1673         Returns True if all of the dates are at midnight ("no time")
   1674         """
-> 1675         return libts.dates_normalized(self.asi8, self.tz)
   1676 
   1677     @cache_readonly

pandas/_libs/tslib.pyx in pandas._libs.tslib.dates_normalized (pandas/_libs/tslib.c:88136)()

AttributeError: 'datetime.timezone' object has no attribute '_transition_info'

Possibly this is due to version differences in my environment (although I am using current versions).

The error appears to be due to pandas expecting a pytz object for the timezone (due to it referencing _transition_info which is not on the datetime.timezone object but is on the pytz.timezone object.

-------------

The error can be fixed by changing evekit-source-mdtools/src/evekit/util/__init__.py to the version below.

# evekit.util package
import datetime
import pytz

def convert_raw_time(raw_time):
    """
    Convert time in milliseconds UTC (since the epoch) to a datetime

    :param raw_time: time in milliseconds UTC (since the epoch)
    :return: raw time converted to datetime
    """
    return datetime.datetime.fromtimestamp(raw_time//1000, pytz.UTC).replace(microsecond=raw_time%1000*1000)

-------------

This problem also presents itself in
Example_1_Data_Extraction.ipynb
Example_1_Data_Extraction_With_Libraries.ipynb
and the images of the cells in the Preliminaries Example 1 - Data Extraction: Make a Graph of Market History.

**Comment by deadlybulb** [comment]
Thanks for the error report.  I can't seem to reproduce your issue.  Can you share the version of python and pandas you're using?  The latest version of the time converter uses timezone like this:

```python
    return datetime.datetime.fromtimestamp(raw_time//1000, datetime.timezone.utc).replace(microsecond=raw_time%1000*1000)
```

which uses the datetime timezone library, but it sounds like that wouldn't work for you.

I'm using python 3.6.1 and pandas 0.20.2.

**Comment by sloveridge** [comment]
Yes I got the bug with the latest version of evekit from here.
python --version
Python 3.6.2

pip freeze
appnope==0.1.0
bleach==2.0.0
bravado==9.1.0
bravado-core==4.8.0
certifi==2017.7.27.1
chardet==3.0.4
cycler==0.10.0
decorator==4.1.2
entrypoints==0.2.3
html5lib==0.999999999
idna==2.5
ipykernel==4.6.1
ipython==6.1.0
ipython-genutils==0.2.0
ipywidgets==6.0.0
jedi==0.10.2
Jinja2==2.9.6
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.1.0
jupyter-console==5.1.0
jupyter-core==4.3.0
MarkupSafe==1.0
matplotlib==2.0.2
mistune==0.7.4
nbconvert==5.2.1
nbformat==4.3.0
notebook==5.0.0
numpy==1.13.1
pandas==0.20.3
pandocfilters==1.4.1
pexpect==4.2.1
pickleshare==0.7.4
prompt-toolkit==1.0.15
ptyprocess==0.5.2
Pygments==2.2.0
pyparsing==2.2.0
python-dateutil==2.6.1
pytz==2017.2
PyYAML==3.12
pyzmq==16.0.2
qtconsole==4.3.0
requests==2.18.3
rfc3987==1.3.7
scipy==0.19.1
simplegeneric==0.8.1
simplejson==3.11.1
six==1.10.0
strict-rfc3339==0.7
swagger-spec-validator==2.1.0
terminado==0.6
testpath==0.3.1
tornado==4.5.1
traitlets==4.3.2
urllib3==1.22
wcwidth==0.1.7
webcolors==1.7
webencodings==0.5.1
widgetsnbextension==2.0.0

Perhaps it is Pandas 0.20.3 that is unhappy with datetime.timezone.utc

**Comment by deadlybulb** [comment]
Actually, I managed to reproduce with my current version which will make it easier to fix.  Could be it's just picky about pytz now.  Thanks again for the report.

**Comment by deadlybulb** [comment]
I fixed this by using pytz as the OP suggested.  I also raised an issue with the pandas team here:

https://github.com/pandas-dev/pandas/issues/17173

It looks like this is a bug on their end, but there's no harm in using pytz here.
